Style/GlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'builds/**/*'