Style/GlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

AllCops:
  Exclude:
    - 'builds/**/*'