[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "galactic-space-trader"
# The game's title. This will show up in the tile bar of your executable.
title = "Galactic Space Trader"
version = "0.1.0"
authors = ["Dee Schaedler"]
icon = "metadata/icon.png"
compile_ruby = true

[dragonruby]
version = "3.2"
edition = "pro"

[dependencies]

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "https://deeschaedler.itch.io/galactic-space-trader"
# Your username on Itch.io.
username = "deeschaedler"
